import { chmodSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { expect, test } from "@playwright/test";
import { launchApp, type AppHandle } from "./fixtures/electron-app";
import { createGitSandbox, type GitSandbox } from "./fixtures/git-sandbox";
import { addRootAndExpand } from "./fixtures/steps";

let sandbox: GitSandbox | null = null;
let handle: AppHandle | null = null;

test.afterEach(async () => {
  if (handle !== null) { await handle.cleanup(); handle = null; }
  sandbox?.cleanup();
  sandbox = null;
});

test("hook refusal explains the failed commit and offers a one-time bypass", async ({}, testInfo) => {
  sandbox = createGitSandbox();
  const repo = sandbox.makeRepo("discovery-hooks");
  writeFileSync(join(repo.path, "README.md"), "# discovery-hooks\nchanged\n");
  sandbox.git(repo.path, "add", "README.md");
  const hook = join(repo.path, ".git", "hooks", "pre-commit");
  writeFileSync(hook, "#!/bin/sh\necho 'fixture lint: change needs a test' >&2\nexit 1\n");
  chmodSync(hook, 0o755);

  handle = await launchApp();
  const { window } = handle;
  await addRootAndExpand(window, handle, sandbox, "discovery-hooks");
  await window.locator(".commit-input").fill("feat: revise discovery fixture");
  await expect(window.locator(".commit-actions .commit-btn")).toBeEnabled();
  await window.screenshot({ path: testInfo.outputPath("3a-before-commit.png") });
  await window.locator(".commit-actions .commit-btn").click();
  const failure = window.locator(".discovery-hook-failure");
  await expect(failure).toContainText("pre-commit refused the commit");
  await expect(failure).toContainText("fixture lint: change needs a test");
  await window.screenshot({ path: testInfo.outputPath("3a-after-hook-refusal.png") });
  await failure.getByRole("button", { name: "Commit without hooks…" }).click();
  await expect(window.locator(".modal--dialog")).toContainText("git commit --no-verify");
  await window.locator(".modal--dialog .modal__cancel").click();
  writeFileSync(hook, "#!/bin/sh\necho 'fixture lint passed' >&2\nexit 0\n");
  await failure.getByRole("button", { name: "Retry commit" }).click();
  await expect(window.locator(".discovery-receipt")).toContainText("pre-commit");
  await window.screenshot({ path: testInfo.outputPath("3a-after-hook-passed.png") });
});

test("ignore dialog explains clone scope and the footer attributes hidden files", async ({}, testInfo) => {
  sandbox = createGitSandbox();
  const repo = sandbox.makeRepo("discovery-ignore", { worktrees: ["feature"] });
  mkdirSync(join(repo.path, ".local", "shots"), { recursive: true });
  writeFileSync(join(repo.path, ".local", "shots", "after.png"), "fixture image\n");

  handle = await launchApp();
  const { window } = handle;
  await addRootAndExpand(window, handle, sandbox, "discovery-ignore");
  await expect(window.locator(".discovery-ignored-footer")).toHaveCount(0);
  await window.screenshot({ path: testInfo.outputPath("4a-before-ignore.png") });
  const row = window.locator(".file-row", { hasText: "after.png" });
  await row.click({ button: "right" });
  await window.getByRole("menuitem", { name: "Ignore…" }).click();
  const dialog = window.locator(".discovery-ignore");
  await expect(dialog).toBeVisible();
  await expect(dialog.locator(".discovery-ignore__destination.is-selected")).toContainText("this clone · 2 worktrees");
  await expect(dialog.locator(".discovery-ignore__preview code").nth(1)).toHaveText("+ /.local/");
  await window.screenshot({ path: testInfo.outputPath("4a-ignore-dialog.png") });
  await dialog.getByRole("button", { name: "Add ignore rule" }).click();
  await expect(window.locator(".discovery-ignored-footer")).toContainText("1 untracked file hidden");
  await window.locator(".discovery-ignored-footer button").hover();
  await expect(window.locator(".discovery-explain")).toContainText(".git/info/exclude");
  await window.screenshot({ path: testInfo.outputPath("4c-after-ignore.png") });
});

test("a repository without active hooks keeps the header unchanged", async ({}, testInfo) => {
  sandbox = createGitSandbox();
  sandbox.makeRepo("discovery-empty");
  handle = await launchApp();
  const { window } = handle;
  await addRootAndExpand(window, handle, sandbox, "discovery-empty");
  await expect(window.getByText("Loading history...")).toBeHidden();
  await expect(window.locator(".discovery-hooks-chip")).toHaveCount(0);
  await expect(window.locator(".lfs-chip")).toHaveCount(0);
  await window.screenshot({ path: testInfo.outputPath("2d-before-empty-repo.png") });
  await window.locator(".wt-header").screenshot({ path: testInfo.outputPath("2d-before-header.png") });
});

test("repository setup shows hook provenance, shadowed LFS and editable ignore layers", async ({}, testInfo) => {
  sandbox = createGitSandbox();
  const repo = sandbox.makeRepo("discovery-setup");
  writeFileSync(join(repo.path, ".gitattributes"), "*.bin filter=lfs diff=lfs merge=lfs -text\n");
  writeFileSync(join(repo.path, ".gitignore"), "*.log\n");
  mkdirSync(join(repo.path, ".husky", "_"), { recursive: true });
  const preCommit = join(repo.path, ".husky", "_", "pre-commit");
  writeFileSync(preCommit, "#!/bin/sh\necho fixture hook ran\n");
  chmodSync(preCommit, 0o755);
  sandbox.git(repo.path, "add", ".gitattributes", ".gitignore", ".husky/_/pre-commit");
  sandbox.git(repo.path, "commit", "-m", "add fixture rules and hook");
  repo.addWorktree("feature");
  sandbox.git(repo.path, "config", "core.hooksPath", ".husky/_");
  const prePush = join(repo.path, ".git", "hooks", "pre-push");
  writeFileSync(prePush, "#!/bin/sh\ngit lfs pre-push \"$@\"\n");
  chmodSync(prePush, 0o755);
  writeFileSync(join(repo.path, ".git", "info", "exclude"), "notes.md\n");
  const fixtureGlobal = join(sandbox.reposDir, "..", "fixture-global-ignore");
  writeFileSync(fixtureGlobal, ".DS_Store\n");
  sandbox.git(repo.path, "config", "core.excludesFile", fixtureGlobal);
  writeFileSync(join(repo.path, "README.md"), "# discovery-setup\nA fixture commit for the hook receipt.\n");
  sandbox.git(repo.path, "add", "README.md");

  handle = await launchApp();
  const { window } = handle;
  await addRootAndExpand(window, handle, sandbox, "discovery-setup");
  await expect(window.getByText("Loading history...")).toBeHidden();
  await window.locator(".commit-input").fill("test: run fixture hook");
  await window.locator(".commit-actions .commit-btn").click();
  await expect(window.locator(".discovery-receipt")).toContainText("pre-commit");
  await expect(window.locator(".discovery-hooks-chip")).toHaveText("hooks 1");
  await expect(window.locator(".lfs-chip--shadowed")).toBeVisible();
  await window.screenshot({ path: testInfo.outputPath("2d-after-hooks-chip.png") });
  await window.locator(".wt-header").screenshot({ path: testInfo.outputPath("2d-after-header.png") });
  const repoRow = window.locator(".repo-row", { hasText: "discovery-setup" }).first();
  await repoRow.click({ button: "right" });
  await expect(window.getByRole("menuitem", { name: "Repository setup…" })).toBeVisible();
  await window.screenshot({ path: testInfo.outputPath("2c-repo-menu.png"), animations: "disabled" });
  await window.getByRole("menuitem", { name: "Repository setup…" }).click();
  const sheet = window.locator(".repository-setup");
  await expect(sheet).toContainText("core.hooksPath");
  await expect(sheet).toContainText("pre-commit");
  await expect(sheet).toContainText("Last ran");
  await expect(sheet).toContainText("pre-push");
  await expect(sheet).toContainText("LFS files may not upload");
  await window.screenshot({ path: testInfo.outputPath("3c-after-hooks-setup.png"), animations: "disabled" });
  await sheet.getByRole("button", { name: "Hook map…" }).click();
  await expect(sheet.locator(".repository-setup__lane button.is-shadowed")).toContainText("pre-push");
  await sheet.locator(".repository-setup__lane button", { hasText: "pre-push" }).click();
  await expect(sheet.locator(".repository-setup__map-detail")).toContainText("shadowed, not run");
  await sheet.locator(".repository-setup__map-detail").scrollIntoViewIfNeeded();
  await window.screenshot({ path: testInfo.outputPath("3b-after-hook-map.png"), animations: "disabled" });
  await sheet.getByRole("button", { name: /Ignore rules/ }).click();
  await expect(sheet.locator(".repository-setup__layer")).toHaveCount(3);
  await sheet.getByLabel("Test a path").fill("notes.md");
  await sheet.getByRole("button", { name: "Test", exact: true }).click();
  await expect(sheet.locator(".repository-setup__tester")).toContainText("Ignored");
  await expect(sheet.locator(".repository-setup__layer.is-winning")).toContainText("notes.md");
  await sheet.getByRole("button", { name: "Edit inline" }).click();
  await sheet.getByLabel("Edit .git/info/exclude").fill("notes.md\nscratch/\n");
  await sheet.getByRole("button", { name: "Save rules" }).click();
  await expect(sheet.getByRole("button", { name: "Edit inline" })).toBeVisible();
  await expect(sheet.locator(".repository-setup__layer", { hasText: "This clone" })).toContainText("scratch/");
  await window.screenshot({ path: testInfo.outputPath("4d-after-ignore-setup.png"), animations: "disabled" });
  await sheet.getByRole("button", { name: "Done" }).click();
  await window.keyboard.press(process.platform === "darwin" ? "Meta+k" : "Control+k");
  await window.locator(".overlay-search input").fill("repository setup");
  const command = window.getByRole("button", { name: /Repository setup… Hooks and ignore rules/ });
  await expect(command).toBeVisible();
  await window.locator(".overlay-panel").screenshot({ path: testInfo.outputPath("2c-command.png"), animations: "disabled" });
  await window.locator(".overlay-search input").press("Tab");
  await expect(command).toBeFocused();
  await command.press("Tab");
  await expect(window.locator(".overlay-search input")).toBeFocused();
  await window.keyboard.press("Enter");
  await expect(window.locator(".repository-setup")).toBeVisible();
});
